name: mirror-falcon-image

on:
  schedule:
    - cron: '3 3 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  copy_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: skopeo login to your registry
        run: echo '${{ secrets.YOUR_REGISTRY_PASSWORD }}' | skopeo login --username  "${{ secrets.YOUR_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.YOUR_REGISTRY }}"
      - name: Login to Crowdstrike registries and Sync images
        env:
          FALCON_CID: ${{ secrets.FALCON_CID }}
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
          FALCON_CLOUD_API: ${{ secrets.FALCON_CLOUD_API }}
          FALCON_CONTAINER_REGISTRY: ${{ secrets.FALCON_CONTAINER_REGISTRY }}
          YOUR_REGISTRY: ${{ secrets.YOUR_REGISTRY }}
          YOUR_REGISTRY_USERNAME: ${{ secrets.YOUR_REGISTRY_USERNAME }}
          YOUR_REGISTRY_PASSWORD: ${{ secrets.YOUR_REGISTRY_PASSWORD }}
        run: |
          bash ${{ github.workspace }}/falcon-registries-logon-and-sync.sh
